# Generated by Django 3.2.8 on 2021-10-11 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('desc', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('familyMember', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.familymember')),
                ('incomeSource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.incomesource')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('desc', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('expenseSource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.expensesource')),
                ('familyMember', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.familymember')),
            ],
        ),
    ]
